OPENCV_VERSION=4.8.0

# Check if file exists, if not download them and unzip them
test -e ${OPENCV_VERSION}.zip || wget https://github.com/opencv/opencv/archive/refs/tags/${OPENCV_VERSION}.zip
test -e opencv-${OPENCV_VERSION} || unzip ${OPENCV_VERSION}.zip
test -e opencv_extra_${OPENCV_VERSION}.zip || wget -O opencv_extra_${OPENCV_VERSION}.zip https://github.com/opencv/opencv_contrib/archive/refs/tags/${OPENCV_VERSION}.zip
test -e opencv_contrib-${OPENCV_VERSION} || unzip opencv_extra_${OPENCV_VERSION}.zip

# Create build folder
cd opencv-${OPENCV_VERSION}
mkdir build
cd build

# Build OpenCV with CUDA in build folder
cmake -D CMAKE_BUILD_TYPE=RELEASE \
-D CMAKE_INSTALL_PREFIX=/usr/local \
-D WITH_TBB=ON \
-D ENABLE_FAST_MATH=1 \
-D CUDA_FAST_MATH=1 \
-D WITH_CUBLAS=1 \
-D WITH_CUDA=ON \
-D BUILD_opencv_cudacodec=ON \
-D WITH_CUDNN=ON \
-D OPENCV_DNN_CUDA=ON \
-D WITH_QT=OFF \
-D WITH_OPENGL=ON \
-D BUILD_opencv_apps=OFF \
-D BUILD_opencv_python2=OFF \
-D OPENCV_GENERATE_PKGCONFIG=ON \
-D OPENCV_PC_FILE_NAME=opencv.pc \
-D OPENCV_ENABLE_NONFREE=ON \
-D OPENCV_EXTRA_MODULES_PATH=../../opencv_contrib-${OPENCV_VERSION}/modules \
-D INSTALL_PYTHON_EXAMPLES=OFF \
-D INSTALL_C_EXAMPLES=OFF \
-D BUILD_EXAMPLES=OFF \
-D CUDA_ARCH_BIN=8.6 \
-D WITH_FFMPEG=ON \
-D CUDNN_INCLUDE_DIR=/usr/include/ \
-D CUDNN_LIBRARY=/usr/lib/x86_64-linux-gnu/libcudnn.so \
..

# Compile using 8 cores
make -j 8

# Persist the VERSION variable into a file
# Delete the file if it already exists
rm -f opencv_version.sh
echo "\
# This file is auto-generated by the build_opencv.sh script.
# It contains the version of OpenCV that was last built by the script.
# Do not modify this file manually.
export "OPENCV_VERSION=${OPENCV_VERSION}"\
" >> opencv_version.sh

# Installs system wide using 8 cores
sudo make -j 8 install

# Add the OpenCV library to the ldconfig cache
sudo ldconfig -v

# To undo the install (in the case you are causing conflicts with another version of OpenCV), run
# $ sudo make uninstall
# in the build folder (where you ran the make install command)